{
    "brief": "Throws an error",
    "category": "compiler_script",
    "description": "This throws an error that can be caught by a try/catch block. An error object of object type _AdaptiveError_ will be available in the catch block. Its 'id' property will be set to 'throw'. The other properties set based on the parameters specified and where this function is called.",
    "functionId": "throw",
    "functionLabel": "throw",
    "parameters": [
        {
            "brief": "Error message",
            "dataType": "string",
            "description": "This is the message that will be included in the _AdaptiveError_ error object available in the catch block.",
            "name": "message"
        },
        {
            "brief": "Optional additional information",
            "description": "Optional additional information that will be available as a 'additional' property in the error object.",
            "optional": true,
            "name": "additional"
        }
    ],
    "pure": true,
    "returns": {
        "dataType": "void"
    },
    "scriptSupport": true
}